# trigger:
# - main

parameters:
- name: pool_image
  displayName: Pool Images
  type: string
  default: ubuntu-latest
  values:
  - ubuntu-latest
  - macOS-latest


variables:
  latex-pdf-file: latex_book

jobs:
- job: Latex_Build
  displayName: Generate `.pdf` from latex file 
  pool:
    vmImage: ${{ parameters.pool_image }}

  steps:
  - script: |
      uname -a
      sudo apt update
    displayName: Test the system's integrity

  - script: ls -la
    displayName: Test the repository structure

  - script: sudo apt-get install -y texlive-full
    displayName: Install `pdflatex` on the VM
  
  - script: |
      ls -l
      pdflatex main.tex
      pdflatex main.tex
      ls -l
    displayName: Compile the main latex file
  
  - script: |
      cp main.pdf /tmp
    displayName: Compile the latex main file

  - publish: /tmp/main.pdf
    artifact: $(latex-pdf-file)