# trigger:
# - main

# parameters:
# - name: pool_image
#   displayName: Pool Images
#   type: string
#   default: ubuntu-latest
#   values:
#   - ubuntu-latest
#   - macOS-latest

variables:
  latex-pdf-file: latex_book
  os-mac: macOS-latest
  os-linux: ubuntu-latest

jobs:
- job: Latex_Build_Ubuntu
  displayName: Build latex project on Linux
  pool:
    vmImage: $(os-linux)

  steps:
  - script: |
      sudo apt update
      sudo apt-get install -y texlive-latex-extra 
    displayName: Update system + install latex package
  
  - script: |
      pdflatex main.tex
      pdflatex main.tex
    displayName: Compile the main latex file
  
  - script: |
      cp main.pdf /tmp
    displayName: Copy the obtained pdf file to /tmp

  - publish: /tmp/main.pdf
    artifact: $(latex-pdf-file)

- job: Latex_Build_macOS
  displayName: Build latex project on macOS
  pool:
    vmImage: $(os-mac)

  steps:
  - script: |
      brew install --cask mactex
      eval "$(/usr/libexec/path_helper)"
      xelatex main.tex
    displayName: Install mactex and build project with xelatex

  - publish: main.pdf
    artifact: $(latex-pdf-file)