# trigger:
# - main

# parameters:
# - name: pool_image
#   displayName: Pool Images
#   type: string
#   default: ubuntu-latest
#   values:
#   - ubuntu-latest
#   - macOS-latest


variables:
  latex-pdf-file: latex_book
  os-mac: macOS-latest
  os-linux: ubuntu-latest

jobs:
- job: Latex_Build_Ubuntu
  displayName: Generate `.pdf` from latex file 
  pool:
    vmImage: $(os-linux)

  steps:
  - script: |
      sudo apt update
    displayName: Test the system's integrity

  - script: sudo apt-get install -y texlive-latex-extra 
    displayName: Install `pdflatex-extra` on the VM
  
  - script: |
      pdflatex main.tex
      pdflatex main.tex
    displayName: Compile the main latex file
  
  - script: |
      cp main.pdf /tmp
    displayName: Compile the latex main file

  - publish: /tmp/main.pdf
    artifact: $(latex-pdf-file)

- job: Latex_Build_macOS
  displayName: Test macOS
  pool:
    vmImage: $(os-mac)

  steps:
  - script: |
      ls -l
      uname -a