name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  # linux-build:
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, 'skip-action')" #https://github.com/marketplace/actions/skip-based-on-commit-message
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - name: Update OS and install latex packages [texlive,biber]
  #       run: |
  #         uname -a
  #         sudo apt update
  #         sudo apt-get install -y texlive-latex-extra 
  #         sudo apt install biber
  #     - name: Compile latex project with pdflatex
  #       run: |
  #         pdflatex main.tex
  #         biber main.bcf
  #         pdflatex main.tex
  #         pdflatex main.tex
  #         ls -l
  #     - name: Create artifact from the compiled pdf book
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: latex-book-linux
  #         path: ./main.pdf
  
  macos-build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip-action')" #https://github.com/marketplace/actions/skip-based-on-commit-message
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install packages [mactex]
        run: |
          brew install --cask mactex
          eval "$(/usr/libexec/path_helper)"
      - name: test tlmgr command
        run: |
          tlmgr --help
          tlmgr update --all
          tlmgr install biber
          tlmgr install biblatex
      - name: Compile latex project with xelatex
        run: |
          xelatex main.tex
          biber main.bcf
          xelatex main.tex
          xelatex main.tex
          ls -la

  
  # book-release:
  #   runs-on: ubuntu-latest
  #   if: "!contains(github.event.head_commit.message, 'skip-action')" #https://github.com/marketplace/actions/skip-based-on-commit-message
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2


  #     - name: Create release with artifact
  #       uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         automatic_release_tag: "latest"
  #         prerelease: true
  #         title: "Latex-Book"
  #         files: |
  #           CHANGELOG.md
  #           main.pdf

  # azure-pipeline-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Azure Pipelines Action
  #       uses: Azure/pipelines@v1
  #       with:
  #         azure-devops-project-url: https://dev.azure.com/robertpoenaru/Overleaf-Book-Template
  #         azure-pipeline-name: 'basavyr.Overleaf-Book-Template'
  #         azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}