name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  github-make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test VM functionality
        run: uname -a
      - name: Update VM
        run: |
          sudo apt update
          which python
  # azure-pipeline-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Azure Pipelines Action
  #       uses: Azure/pipelines@v1
  #       with:
  #         azure-devops-project-url: https://dev.azure.com/robertpoenaru/Overleaf-Book-Template
  #         azure-pipeline-name: 'basavyr.Overleaf-Book-Template'
  #         azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}