name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  github-make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test VM functionality
        run: uname -a
      - name: Update VM
        run: |
          sudo apt update
      - name: Install latex
        run: |
          sudo apt-get install -y texlive-full
      - name: Compile latex book
        run: |
          ls -l
          pdflatex main.pdf
          ls -l
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: latex-book
          path: ./main.pdf
  # azure-pipeline-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Azure Pipelines Action
  #       uses: Azure/pipelines@v1
  #       with:
  #         azure-devops-project-url: https://dev.azure.com/robertpoenaru/Overleaf-Book-Template
  #         azure-pipeline-name: 'basavyr.Overleaf-Book-Template'
  #         azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}