name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  github-make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test VM functionality
        run: uname -a
      - name: Update VM
        run: |
          sudo apt update
          which python
  azure-pipeline-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/robertpoenaru/Latex-CI-CD
          azure-pipeline-name: 'GitHub-DevOps'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}